<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-04T09:56:40 EET" name="Default suite" finished-at="2021-03-04T09:57:01 EET" duration-ms="21786">
    <groups>
    </groups>
    <test started-at="2021-03-04T09:56:40 EET" name="Default test" finished-at="2021-03-04T09:57:01 EET" duration-ms="21786">
      <class name="Tests.ChildRegistrationTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.ChildRegistrationTest@306cf3ea]" started-at="2021-03-04T09:56:40 EET" name="setUp" finished-at="2021-03-04T09:56:40 EET" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openHomePage()[pri:0, instance:Tests.ChildRegistrationTest@306cf3ea]" started-at="2021-03-04T09:56:40 EET" name="openHomePage" finished-at="2021-03-04T09:56:43 EET" duration-ms="3313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHomePage -->
        <test-method signature="pdfUploadTest()[pri:0, instance:Tests.ChildRegistrationTest@306cf3ea]" started-at="2021-03-04T09:56:43 EET" name="pdfUploadTest" finished-at="2021-03-04T09:57:01 EET" duration-ms="18378" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Failas įkeltas sėkmingai!] but found [×
Failas įkeltas sėkmingai!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Failas įkeltas sėkmingai!] but found [×
Failas įkeltas sėkmingai!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Tests.ChildRegistrationTest.pdfUploadTest(ChildRegistrationTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pdfUploadTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.ChildRegistrationTest@306cf3ea]" started-at="2021-03-04T09:57:01 EET" name="tearDown" finished-at="2021-03-04T09:57:01 EET" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.ChildRegistrationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
